# Nome da pipeline
name: Run Basic Test

# Gatilho de execução
trigger:
  branches:
    include:
      - main

# Definição dos trabalhos
jobs:
  - job: cypress-run
    pool:
      vmImage: 'ubuntu-latest'

    steps:
      - task: UseNode@1
        inputs:
          version: '16.x'
          checkLatest: true

      - script: |
          npm install
        displayName: 'Instalar dependências'
      
      - script: |
          npx cypress run
        displayName: 'Executar testes do Cypress'
